server:
  port: 8848
  servlet:
    context-path: /aili
# 关闭默认图标
spring:
  mvc:
    favicon:
      enabled: false
  # 关闭模板引擎的缓存
  thymeleaf:
    cache: false
  # 配置国际化
  messages:
    basename: i18n.wuhu